[2023-09-23T13:43:25.483+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.dbt_run_tests manual__2023-09-23T13:41:31.559891+00:00 [queued]>
[2023-09-23T13:43:25.499+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.dbt_run_tests manual__2023-09-23T13:41:31.559891+00:00 [queued]>
[2023-09-23T13:43:25.499+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-23T13:43:25.527+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_run_tests> on 2023-09-23 13:41:31.559891+00:00
[2023-09-23T13:43:25.535+0000] {standard_task_runner.py:57} INFO - Started process 438 to run task
[2023-09-23T13:43:25.540+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'dbt_run_tests', 'manual__2023-09-23T13:41:31.559891+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp5bgu2xmm']
[2023-09-23T13:43:25.546+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask dbt_run_tests
[2023-09-23T13:43:25.653+0000] {task_command.py:415} INFO - Running <TaskInstance: main_dag.dbt_run_tests manual__2023-09-23T13:41:31.559891+00:00 [running]> on host 4ef300bfa8d2
[2023-09-23T13:43:25.881+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='dbt_run_tests' AIRFLOW_CTX_EXECUTION_DATE='2023-09-23T13:41:31.559891+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-23T13:41:31.559891+00:00'
[2023-09-23T13:43:25.897+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-23T13:43:25.900+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt test --profiles-dir /.dbt --project-dir /dbt_project']
[2023-09-23T13:43:25.965+0000] {subprocess.py:86} INFO - Output:
[2023-09-23T13:43:32.034+0000] {subprocess.py:93} INFO - [0m13:43:32  Running with dbt=1.5.3
[2023-09-23T13:43:32.293+0000] {subprocess.py:93} INFO - [0m13:43:32  Registered adapter: postgres=1.5.3
[2023-09-23T13:43:32.588+0000] {subprocess.py:93} INFO - [0m13:43:32  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-09-23T13:43:32.590+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2023-09-23T13:43:32.591+0000] {subprocess.py:93} INFO - - models.dbt_supermarket_data_engineering.example
[2023-09-23T13:43:32.642+0000] {subprocess.py:93} INFO - [0m13:43:32  Found 5 models, 0 tests, 1 snapshot, 0 analyses, 718 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics, 0 groups
[2023-09-23T13:43:32.646+0000] {subprocess.py:93} INFO - [0m13:43:32
[2023-09-23T13:43:32.647+0000] {subprocess.py:93} INFO - [0m13:43:32  Nothing to do. Try checking your model configs and model specification args
[2023-09-23T13:43:35.511+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-09-23T13:43:35.718+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=dbt_run_tests, execution_date=20230923T134131, start_date=20230923T134325, end_date=20230923T134335
[2023-09-23T13:43:35.807+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-23T13:43:35.836+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
