[2023-09-20T10:29:35.976+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.mongo_to_postgres manual__2023-09-20T10:29:16.685666+00:00 [queued]>
[2023-09-20T10:29:35.988+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.mongo_to_postgres manual__2023-09-20T10:29:16.685666+00:00 [queued]>
[2023-09-20T10:29:35.989+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T10:29:36.024+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): mongo_to_postgres> on 2023-09-20 10:29:16.685666+00:00
[2023-09-20T10:29:36.030+0000] {standard_task_runner.py:57} INFO - Started process 103 to run task
[2023-09-20T10:29:36.034+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'mongo_to_postgres', 'manual__2023-09-20T10:29:16.685666+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp2r6tkp22']
[2023-09-20T10:29:36.215+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask mongo_to_postgres
[2023-09-20T10:29:36.275+0000] {task_command.py:415} INFO - Running <TaskInstance: main_dag.mongo_to_postgres manual__2023-09-20T10:29:16.685666+00:00 [running]> on host 7fbbdad7685a
[2023-09-20T10:29:36.367+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='mongo_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T10:29:16.685666+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T10:29:16.685666+00:00'
[2023-09-20T10:29:36.429+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_scripts/mongodb_to_postgres.py", line 38, in main
    schema_has_changed_bool = test_mongodb_schema_change.test_if_schema_has_changed(
  File "/opt/airflow/dags/dag_scripts/tests/test_mongodb_schema_change.py", line 29, in test_if_schema_has_changed
    new_columns_flag = test_schema_change_if_new_columns(
  File "/opt/airflow/dags/dag_scripts/tests/test_mongodb_schema_change.py", line 56, in test_schema_change_if_new_columns
    assert len(expected_columns_set.difference(raw_mongo_columns_set)) == 0
AttributeError: 'list' object has no attribute 'difference'
[2023-09-20T10:29:36.442+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=main_dag, task_id=mongo_to_postgres, execution_date=20230920T102916, start_date=20230920T102935, end_date=20230920T102936
[2023-09-20T10:29:36.493+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task mongo_to_postgres ('list' object has no attribute 'difference'; 103)
[2023-09-20T10:29:36.530+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T10:29:36.764+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
