[2023-09-21T05:30:47.257+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.run_dbt manual__2023-09-21T05:30:24.751227+00:00 [queued]>
[2023-09-21T05:30:47.269+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.run_dbt manual__2023-09-21T05:30:24.751227+00:00 [queued]>
[2023-09-21T05:30:47.270+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-21T05:30:47.291+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): run_dbt> on 2023-09-21 05:30:24.751227+00:00
[2023-09-21T05:30:47.297+0000] {standard_task_runner.py:57} INFO - Started process 113 to run task
[2023-09-21T05:30:47.301+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'run_dbt', 'manual__2023-09-21T05:30:24.751227+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmptu_74cky']
[2023-09-21T05:30:47.304+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask run_dbt
[2023-09-21T05:30:47.366+0000] {task_command.py:415} INFO - Running <TaskInstance: main_dag.run_dbt manual__2023-09-21T05:30:24.751227+00:00 [running]> on host 8f5aacc3809f
[2023-09-21T05:30:47.491+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2023-09-21T05:30:24.751227+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-21T05:30:24.751227+00:00'
[2023-09-21T05:30:47.494+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-21T05:30:47.495+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --profiles-dir /.dbt --project-dir /opt/***/dbt_project']
[2023-09-21T05:30:47.527+0000] {subprocess.py:86} INFO - Output:
[2023-09-21T05:30:53.989+0000] {subprocess.py:93} INFO - [0m05:30:53  Running with dbt=1.5.3
[2023-09-21T05:30:54.331+0000] {subprocess.py:93} INFO - [0m05:30:54  Registered adapter: postgres=1.5.3
[2023-09-21T05:30:54.607+0000] {subprocess.py:93} INFO - [0m05:30:54  Unable to do partial parsing because of a version mismatch
[2023-09-21T05:30:59.448+0000] {subprocess.py:93} INFO - [0m05:30:59  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-09-21T05:30:59.449+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2023-09-21T05:30:59.449+0000] {subprocess.py:93} INFO - - models.dbt_supermarket_data_engineering.example
[2023-09-21T05:30:59.524+0000] {subprocess.py:93} INFO - [0m05:30:59  Found 5 models, 0 tests, 1 snapshot, 0 analyses, 718 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics, 0 groups
[2023-09-21T05:30:59.532+0000] {subprocess.py:93} INFO - [0m05:30:59
[2023-09-21T05:30:59.572+0000] {subprocess.py:93} INFO - [0m05:30:59
[2023-09-21T05:30:59.573+0000] {subprocess.py:93} INFO - [0m05:30:59  Finished running  in 0 hours 0 minutes and 0.04 seconds (0.04s).
[2023-09-21T05:30:59.574+0000] {subprocess.py:93} INFO - [0m05:30:59  Encountered an error:
[2023-09-21T05:30:59.575+0000] {subprocess.py:93} INFO - Database Error
[2023-09-21T05:30:59.575+0000] {subprocess.py:93} INFO -   connection to server at "postgres_project_data" (172.25.0.2), port 5433 failed: Connection refused
[2023-09-21T05:30:59.575+0000] {subprocess.py:93} INFO -   	Is the server running on that host and accepting TCP/IP connections?
[2023-09-21T05:30:59.575+0000] {subprocess.py:93} INFO - 
[2023-09-21T05:31:01.857+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-09-21T05:31:01.872+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-09-21T05:31:01.876+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=main_dag, task_id=run_dbt, execution_date=20230921T053024, start_date=20230921T053047, end_date=20230921T053101
[2023-09-21T05:31:01.959+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 41 for task run_dbt (Bash command failed. The command returned a non-zero exit code 2.; 113)
[2023-09-21T05:31:02.013+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-21T05:31:02.048+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
