[2023-09-20T12:28:48.786+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.run_dbt manual__2023-09-20T12:28:26.912346+00:00 [queued]>
[2023-09-20T12:28:48.799+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.run_dbt manual__2023-09-20T12:28:26.912346+00:00 [queued]>
[2023-09-20T12:28:48.799+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T12:28:48.819+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): run_dbt> on 2023-09-20 12:28:26.912346+00:00
[2023-09-20T12:28:48.825+0000] {standard_task_runner.py:57} INFO - Started process 92 to run task
[2023-09-20T12:28:48.829+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'run_dbt', 'manual__2023-09-20T12:28:26.912346+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp9lgcfi58']
[2023-09-20T12:28:49.007+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask run_dbt
[2023-09-20T12:28:49.060+0000] {task_command.py:415} INFO - Running <TaskInstance: main_dag.run_dbt manual__2023-09-20T12:28:26.912346+00:00 [running]> on host 26cc37751b8e
[2023-09-20T12:28:49.174+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T12:28:26.912346+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T12:28:26.912346+00:00'
[2023-09-20T12:28:49.176+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-20T12:28:49.176+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --profiles-dir /.dbt --project-dir /home/***/dbt_project']
[2023-09-20T12:28:49.189+0000] {subprocess.py:86} INFO - Output:
[2023-09-20T12:28:54.461+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2023-09-20T12:28:54.462+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2023-09-20T12:28:54.462+0000] {subprocess.py:93} INFO - 
[2023-09-20T12:28:54.463+0000] {subprocess.py:93} INFO - Error: Invalid value for '--project-dir': Path '/home/***/dbt_project' does not exist.
[2023-09-20T12:28:54.669+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-09-20T12:28:54.682+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-09-20T12:28:54.686+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=main_dag, task_id=run_dbt, execution_date=20230920T122826, start_date=20230920T122848, end_date=20230920T122854
[2023-09-20T12:28:54.710+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task run_dbt (Bash command failed. The command returned a non-zero exit code 2.; 92)
[2023-09-20T12:28:54.745+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T12:28:54.777+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
